### ISSUE TITLE
New custom keyboard fails

### ISSUE THREAD

**Issue by subzero79** [onedr0p/telegram-sonarr-bot#9] opened 2016-01-03 02:51 UTC
The new custom keyboards introduced with PR #8 by @jayrox work well at first two sends, series search, and profile but fails at selecting the destination path, bot doesn't return anything and the interactive log also does not show anything.

Is there a way to debug the js to see what's sending to sonarr's API?

**Comment by jayrox** [comment] 2016-01-03 03:35
how many folders do you have set up? i recall seeing another issue where someone was having an issue with only one folder.

**Comment by subzero79** [comment] 2016-01-03 03:49
I have two folders, /tv/folder1 /tv/folder2

added after line 465 looks like this

```
  var opts = {
    'disable_web_page_preview': true,
    'parse_mode': 'Markdown',
    'selective': 2,
    'reply_markup': JSON.stringify(keyboard),
  };
  console.log(opts)
  bot.sendMessage(chatId, response.join('\n'), opts);
}
```

Doesn't get more verbose than normal, just the same output

```
root@a838a1705550:/opt/telegram-sonarr-bot# node sonarr.js 
Welcome to the sonarr bot Sonarr_bot!
110642629 requested to search for series Vinyl
110642629 requested to get profiles list
110642629 requested to get folder list
```

**Comment by jayrox** [comment] 2016-01-03 03:50
ok,

add `console.log(folderList)`
on line 417

**Comment by subzero79** [comment] 2016-01-03 03:53
Removed the after 465 line, added 417 looked like this 

```
  if (seriesList === undefined || seriesId === undefined || folderList === undefined) {
    replyWithError(chatId, new Error('Error: something went wrong, try searching again'));
  }
  console.log(folderList)
  var folder = _.filter(folderList, function(item) {
    return item.path == folderName;
  })[0];
```

but same log as above

**Comment by jayrox** [comment] 2016-01-03 03:57
ok so its not getting into the the handler. looks like its failing in the previous handler.

does it say in the telegram chat "Found # folders" and give a list?

put a `console.log(keyboardList)` on line 385
and a `console.log(opts)` after line 402

**Comment by subzero79** [comment] 2016-01-03 04:03
Yes, the path list is displayed correctly found 2 folders etc, here's the response log but is basically the reply from sonarr and then the push to the bot. 

```
110642629 requested to search for series Vinyl
110642629 requested to get profiles list
110642629 requested to get folder list
[ [ '/tv/ricardo/' ], [ '/tv/kass/' ] ]
{ disable_web_page_preview: true,
  parse_mode: 'Markdown',
  selective: 2,
  reply_markup: '{"keyboard":[["/tv/ricardo/"],["/tv/kass/"]],"one_time_keyboard":true}' }
```

**Comment by jayrox** [comment] 2016-01-03 04:08
ok that looks good, so back to line 417

add 
```
console.log("foldername: " + folderName)
console.log(folderList)
```

**Comment by subzero79** [comment] 2016-01-03 04:26
The same output as before. I was trying to remove one of the path's from sonarr, but i can't remember the where was that option

**Comment by jayrox** [comment] 2016-01-03 04:28
so the `console.log("foldername: " + folderName)` didnt write to the log?

**Comment by subzero79** [comment] 2016-01-03 04:31
Nope is the same log as before.

**Comment by jayrox** [comment] 2016-01-03 04:38
i'll be around tomorrow also, add a reply to this issue when you are available and i'll keep trying. or possibly throw up a version with a boat load of log items for everything

**Comment by subzero79** [comment] 2016-01-03 05:28
Now is displaying the state

```
110642629 requested to search for series Vinyl
state: 1
110642629 requested to get profiles list
state: 2
110642629 requested to get folder list
[ [ '/tv/ricardo/' ], [ '/tv/kass/' ] ]
{ disable_web_page_preview: true,
  parse_mode: 'Markdown',
  selective: 2,
  reply_markup: '{"keyboard":[["/tv/ricardo/"],["/tv/kass/"]],"one_time_keyboard":true}' }
```

**Comment by jayrox** [comment] 2016-01-03 08:29
i think i know what the problem is.
the message handler is watching for `/` as the first character and treats it like a command. your paths start with a `/`  so it thinks the path is a command. which is why i can't reproduce cause i'm on a window's device using paths that start with `\\`

change lines 221 - 228 to:
```
bot.on('message', function(msg) {
  var chatId = msg.chat.id;
  var fromId = msg.from.id;
  // If the message is a command, ignore it.
  
  var currentState = cache.get('state' + fromId);
  if(msg.text[0] != '/' || (currentState == state.FOLDER && msg.text[0] == '/')) {
    // Check cache to determine state, if cache empty prompt user to start a movie search
    if (currentState === undefined) {
```

**Comment by subzero79** [comment] 2016-01-03 09:04
Nailed there, i get to pass the next step, where to select monitor, but then again no reply when i select monitor future or any.

**Comment by jayrox** [comment] 2016-01-03 17:38
awesome! ok so, state 4 logs the message but nothing happens after?

after 246 add: `console.log("seriesmonitor: "+seriesMonitor)`
after 483 add
```
  console.log("seriesListLen: " + seriesList.length)
  console.log("profileListLen: " + profileList.length)
  console.log("folderListLen: " + folderList.length)
  console.log("monitorListLen: " + monitorList.length)
```

after 492 add `console.log(series)`
after 498 add `console.log(profile)`
after 504 add `console.log(folder)`
after 510 add `console.log(monitor)`


handleSeriesMonitor should now look similar to:

```
function handleSeriesMonitor(chatId, fromId, monitorType) {
  var seriesId = cache.get('seriesId' + fromId);
  var seriesList = cache.get('seriesList' + fromId);
  var profileId = cache.get('seriesProfileId' + fromId);
  var profileList = cache.get('seriesProfileList' + fromId);
  var folderId = cache.get('seriesFolderId' + fromId);
  var folderList = cache.get('seriesFolderList' + fromId);
  var monitorList = cache.get('seriesMonitorList' + fromId);

  if (folderList === undefined || profileList === undefined || seriesList === undefined || monitorList === undefined) {
    bot.sendMessage(chatId, 'Oh no! Something went wrong, try searching again');
  }
  
  console.log("seriesListLen: " + seriesList.length)
  console.log("profileListLen: " + profileList.length)
  console.log("folderListLen: " + folderList.length)
  console.log("monitorListLen: " + monitorList.length)
    
  var series = _.filter(seriesList, function(item) {
    return item.id == seriesId;
  })[0];

  console.log(series)

  var profile = _.filter(profileList, function(item) {
    return item.id == profileId;
  })[0];

  console.log(profile)

  var folder = _.filter(folderList, function(item) {
    return item.id == folderId;
  })[0];
  
  console.log(folder)

  var monitor = _.filter(monitorList, function(item) {
    return item.type == monitorType;
  })[0];
  
  console.log(monitor)
```

**Comment by subzero79** [comment] 2016-01-03 21:26
Get's confusing with all the lines added from before, can you put in paste bin the patch diff file?

**Comment by jayrox** [comment] 2016-01-03 21:29
https://github.com/jayrox/telegram-sonarr-bot/blob/master/sonarr.js

**Comment by subzero79** [comment] 2016-01-03 21:35
I added the lines, I have your repo pulled with the slash correction. Do i don't have the old log lines so this is when it reaches monitor

```
110642629 requested to search for series Vinyl
110642629 requested to get profiles list
110642629 requested to get folder list
110642629 requested to get monitor list
seriesmonitor: none
seriesListLen: 1
profileListLen: 8
folderListLen: 2
monitorListLen: 5
{ id: 1,
  title: 'Vinyl',
  year: 2016,
  tvdbId: 299400,
  titleSlug: 'vinyl',
  seasons: [ { seasonNumber: 1, monitored: false } ],
  keyboard_value: 'Vinyl - 2016' }
{ id: 2, name: 'SD', label: 'SD', profileId: 2 }
undefined
{ id: 3, type: 'none' }
```

**Comment by jayrox** [comment] 2016-01-03 21:39
ok i just put in a bunch more console.logs in my fork, can you update again and send me the log?

also, if you want you can message me on telegram: @jayrox

**Comment by onedr0p** [comment] 2016-01-03 23:38
Looks like this is fixed for now, closing. I opened a new issue for the profile failing in #12

**Closed by onedr0p** 2016-01-03 23:38 UTC
Labels: bug
