### ISSUE TITLE
[Issue] Error getting folders?

### ISSUE THREAD

**Issue by causefx** [onedr0p/telegram-sonarr-bot#6] opened 2015-12-14 05:17 UTC
This the error it throws...

163345100 requested to search for movie game of
163345100 requested to get profiles list
163345100 requested to get folder list
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"[Error]: Bad Request: can't parse message text: Can't find end of the entity starting at byte offset 40"}
    at C:\telegram-sonarr-bot\node_modules\node-telegram-bot-api\src\telegram.js:104:15
    at tryCatcher (C:\telegram-sonarr-bot\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\telegram-sonarr-bot\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\telegram-sonarr-bot\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\telegram-sonarr-bot\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\telegram-sonarr-bot\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\telegram-sonarr-bot\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\telegram-sonarr-bot\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:384:17)

**Comment by causefx** [comment] 2015-12-14 05:27
oh and by the way, in Sonarr, i only have one folder path set up...

**Comment by onedr0p** [comment] 2015-12-14 05:37
It looks like this is a problem with the library, but I maybe wrong.

In the package.json, change
`"node-telegram-bot-api": "0.15.0",` to "node-telegram-bot-api": "^0.17.0",` and rerun npm install

**Comment by causefx** [comment] 2015-12-14 05:52
error on startup after install:
![image](https://cloud.githubusercontent.com/assets/16184466/11773808/30d84ba4-a1ec-11e5-89f5-8cf8fd519242.png)

**Comment by causefx** [comment] 2015-12-14 05:55
just saw the "^" that I copied from your code... removed it and it installed.  but its still doing the same thing...

![image](https://cloud.githubusercontent.com/assets/16184466/11773846/94c04f86-a1ec-11e5-82f1-e47b2c503eec.png)

**Comment by causefx** [comment] 2015-12-14 05:57
sorry for the multiple posts, but i checked my sonarr logs and saw this after it tried to get folder list:
![image](https://cloud.githubusercontent.com/assets/16184466/11773874/d345ebbc-a1ec-11e5-83b4-e088ffddf1e1.png)

**Comment by onedr0p** [comment] 2015-12-14 06:13
My guess is you don't have any root paths set up in Sonarr.  You can try to add one in the Add Series page of the web app.

1. Goto Add Series
2. Search for Show
3. On path drop down choose 'Add a different path'
4. Browse for the top level folder of your TV Shows
5. Click the green arrow to add to your root paths.

Now.. hopefully the bot will pick up the change when it sends a API request to the [rootfolder endpoint](https://github.com/Sonarr/Sonarr/wiki/Rootfolder).

If this fixes your issue I'll have to write in a condition to warn about no folders found or something.

**Comment by causefx** [comment] 2015-12-14 06:25
I have a ton of shows already so I would have thought it would have used the paths in my recent "area"
![image](https://cloud.githubusercontent.com/assets/16184466/11774267/8b5362fe-a1f0-11e5-9f5e-34fba38a02d3.png)

After I try and add it....
![image](https://cloud.githubusercontent.com/assets/16184466/11774283/bdcf1368-a1f0-11e5-81cf-7489e39011b6.png)

**Comment by onedr0p** [comment] 2015-12-14 06:32
Please post the output of `node --version` and `npm --version`

**Comment by causefx** [comment] 2015-12-14 06:33
here ya go :) thanks man....
![image](https://cloud.githubusercontent.com/assets/16184466/11774399/ed71acc4-a1f1-11e5-8d4d-86e7a5698b76.png)

**Comment by onedr0p** [comment] 2015-12-14 06:41
Thanks for the quick responses, we will get this narrowed down. But maybe later in this day if you're free, it's getting really late here.

For now there's a few things you can try if you're up to it:
Re-downloading this repo files and running `npm install` / copying the config over
Resetting your bot token...
Downgrading (if you can) node to v4.2.3 and then running `npm install npm -g` to update npm...

Sorry you're having issues, it's very odd that it gets to the one step and errors out.

**Comment by causefx** [comment] 2015-12-14 06:42
i'm down for that, I'll give those a whirl and report back...  yeah it's pretty late here too...  thanks for your help.

**Comment by onedr0p** [comment] 2015-12-14 06:43
Your drive with the shows isn't a network drive is it?

**Comment by causefx** [comment] 2015-12-14 06:50
yes and no, i'm running Sonarr on a NAS and running your app on a VM on that same NAS

**Comment by causefx** [comment] 2015-12-14 06:50
BTW, just downgraded and did a clean install and same error persists.

**Comment by onedr0p** [comment] 2015-12-14 06:57
> yes and no, i'm running Sonarr on a NAS and running your app on a VM on that same NAS

This might be the issue. Any chance you are able to install node on the NAS and give it a shot instead of running it on the VM?

**Comment by causefx** [comment] 2015-12-14 06:59
not sure if Node js and QNAP work too well but i'll try :)

**Comment by onedr0p** [comment] 2015-12-14 07:10
Sounds good, we can also use curl to test out what root folders are returned (if any). This program might already be installed on your NAS.

```curl -H "X-Api-Key: SONARR_API_KEY" http://localhost:SONARR_PORT/SONARR_BASEURL/api/rootfolder```

That command should return a whole list of paths in JSON format.

**Comment by causefx** [comment] 2015-12-14 07:14
returned nada :(
![image](https://cloud.githubusercontent.com/assets/16184466/11774940/940d75a4-a1f7-11e5-9b05-b2c360be5eca.png)

**Comment by onedr0p** [comment] 2015-12-14 07:17
Make sure the SONARR_BASEURL is set correctly, or remove it if you don't have one.

**Comment by causefx** [comment] 2015-12-14 07:18
LOL, just saw that as i looked at the image again....

![image](https://cloud.githubusercontent.com/assets/16184466/11774990/3bdb6b06-a1f8-11e5-919d-efc6303701f5.png)

**Comment by onedr0p** [comment] 2015-12-14 07:26
Huh, no difference here at all! So odd! I'm gonna call it a night and sleep on it. My telegram username is onedr0p, we can talk more tomorrow on there. Feel free to get a hold of me when you're free.

**Comment by causefx** [comment] 2015-12-14 07:27
for sure, thanks man, good night!

**Comment by onedr0p** [comment] 2015-12-14 07:29
Lastly, the error looks to be on Telegram end. Look at the error code it spits out to you **400** and it's listed on here as being one of many problems:

https://core.telegram.org/api/errors

**Comment by onedr0p** [comment] 2015-12-14 07:32
Maybe try creating a whole new bot.

**Comment by causefx** [comment] 2015-12-14 07:33
ok lemme try

**Comment by causefx** [comment] 2015-12-14 07:36
LOL, crap, same error.

**Comment by onedr0p** [comment] 2015-12-14 07:37
Make sure you stop the bot whenever you make changes to the config file.

**Comment by causefx** [comment] 2015-12-14 07:38
yup i did all that...

quick question tho, in the code when it sends the request for profile and the user answers, it now moves to the process to get the folders, and lists them for the user to pick, what happens when there is only one folder?  Does it skip the step? or does is error out because there is no list to choose?

**Comment by causefx** [comment] 2015-12-14 07:42
reason i ask is because i dont see an if statement here: 
then(function(folders) {
    console.log(fromId + ' requested to get folder list');

    var folderList = [];
    var response = ['*Found ' + folders.length + ' folders:*'];
    _.forEach(folders, function(n, key) {
	  folderList.push({
	    "id": key + 1,
	    "path": n.path,
	    "folderId": n.id
	  });

	  response.push('*' + (key + 1) + '*) ' + n.path);
    });

    response.push('\n`/f [n]` to continue...');

**Comment by onedr0p** [comment] 2015-12-14 07:42
Currently it will still have a list, but with only 1 option. In the code it will throw an error if no folders are found, but it definitely finds yours because that is not the error we see.

**Comment by onedr0p** [comment] 2015-12-14 07:44
There isn't a need for an if statement there. It will loop thru as many folders are found and append it to the response.

**Comment by causefx** [comment] 2015-12-14 07:46
gotcha, ok we will mess with it tomorrow :)

**Comment by subzero79** [comment] 2015-12-16 00:18
If you have docker in QNAP you can try this image

https://hub.docker.com/r/subzero79/docker-telegram-sonarr-bot/builds/

**Comment by causefx** [comment] 2015-12-16 01:09
@subzero79 DUDE!!!!!! Thank you!!!!!!!!!

My dumbass didnt even know dockers were available on QNAP now... they added it on 4.2 and i didnt even see after the upgrade!!!!!! lol....  gna try this now....

**Comment by onedr0p** [comment] 2015-12-16 01:28
@causefx Any luck? 

@subzero79 does that build update to new versions I publish?

**Comment by subzero79** [comment] 2015-12-16 01:34
Yes, check the docker file at github, it just wget the zip file from your repo, if there is any changes i can go to docker hub and trigger the automated build. 
Automated builds can be triggered from changes in my github repo. 
Maybe we can setup a webhook to your repo to activate the hub automated build in case you commit changes.

**Comment by onedr0p** [comment] 2015-12-16 01:39
Good plan, let me know if there's anything you need from me. If you want, https://github.com/onedr0p/telegram-couchpotato-bot could use a hub too ;)

**Comment by subzero79** [comment] 2015-12-16 02:18
I have url trigger for the sonarr one, how can i send it to you?

**Comment by onedr0p** [comment] 2015-12-16 03:50
send me a message on telegram @onedr0p

**Comment by causefx** [comment] 2015-12-16 18:51
installed the docker and it tried to start but it was looking for the config file like your docker says but for some reason i cant run the docker command under Docker in my container station because of this error:

Cannot connect to the Docker daemon. Is the docker daemon running on this host?

so i tried to start the daemon and got these errors:

INFO[0000] API listen on /var/run/docker.sock                                                                                                     
ERRO[0000] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded.         
WARN[0000] Running modprobe bridge br_netfilter failed with message: modprobe: can't change directory to '/lib/modules': No such file or directory
, error: exit status 1                                                                                                                            
WARN[0000] Running modprobe nf_nat failed with message: `modprobe: can't change directory to '/lib/modules': No such file or directory`, error: ex
it status 1                                                                                                                                       
FATA[0000] Error starting daemon: Error initializing network controller: error obtaining controller instance: Failed to create NAT chain: Iptables

:(

half way there though :)

**Comment by onedr0p** [comment] 2015-12-16 19:37
> Cannot connect to the Docker daemon. Is the docker daemon running on this host?

I was getting this problem yesterday as well and I just had to sudo all my commands with docker. This probably isn't the way you want this to work, but it's a temporary fix.

**Comment by subzero79** [comment] 2015-12-16 20:58
How does docker work on Qnap is it cli or has webui?

**Comment by causefx** [comment] 2015-12-16 22:11
It's a webui

**Comment by subzero79** [comment] 2015-12-16 22:41
So can you run any other images? looks like docker is not enabled.
You should try in the webui then

**Comment by causefx** [comment] 2015-12-16 23:28
I can. That command is from the docker container.

**Comment by subzero79** [comment] 2015-12-17 00:24
I don't understand, why are you trying to run docker commands inside a container?

**Comment by causefx** [comment] 2015-12-17 01:05
Docker it's self is a container. Should I just ssh into my machine and run the commands for docker there? 

I'm not familiar with the qnap container station.

**Comment by subzero79** [comment] 2015-12-17 01:10
Seems to be easier to use the webUI of QNAP. We are going in circles here, i really don't know who the QNAP platform works. Is there a support forum where you can ask how it works?

**Comment by causefx** [comment] 2015-12-17 01:28
I agree.  I'm sure there are forums and I will check them out. Thanks for your help. I really appreciate it.

**Comment by onedr0p** [comment] 2016-01-03 00:19
Closing this issue, if the issue still comes up please let me know.

**Closed by onedr0p** 2016-01-03 00:19 UTC
Labels: bug

**Comment by onedr0p** [comment] 2016-03-11 01:35
This error is actually caused by a non-closing underscore. Removing the underscore in the path would solve this problem.
