### ISSUE TITLE
Exception 400

### ISSUE THREAD

**Issue by crxdelsol** [onedr0p/telegram-sonarr-bot#43] opened 2016-04-11 08:28 UTC
The following error occurred:

```
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"[Error]: Bad Request: Can't parse message text: Can't find end of the entity starting at byte offset 22"}
    at /path/to/telegram-sonarr-bot/node_modules/node-telegram-bot-api/src/telegram.js:121:15
    at tryCatcher (/path/to/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/path/to/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/path/to/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/path/to/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/path/to/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/path/to/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/path/to/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

**Comment by onedr0p** [comment] 2016-04-12 22:34
This is a duplicate of #41

**Closed by onedr0p** 2016-04-12 22:34 UTC
