### ISSUE TITLE
Error when choosing series type!

### ISSUE THREAD

**Issue by frankjath** [onedr0p/telegram-sonarr-bot#41] opened 2016-03-11 00:04 UTC
found the following series types standard,airs daily,anime

I then select standard and it gives me this error and doesn't proceed...

`Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"[Error]: Bad Request: Can't parse message text: Can't find end of the entity starting at byte offset 22"}
    at /Users/frankjath/telegram-sonarr-bot/node_modules/node-telegram-bot-api/src/telegram.js:121:15
    at tryCatcher (/Users/frankjath/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/frankjath/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/frankjath/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/frankjath/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/frankjath/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/frankjath/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/frankjath/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

I have tried adding different tv shows.

**Comment by onedr0p** [comment] 2016-03-11 00:30
There is a similar issue #6 but.. in that issue there was never a solution, so maybe it just started working for him. It doesn't appear to be a problem with the bot itself, but more of a problem on telegrams end. This error `Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"[Error]: Bad Request: Can't parse message text: Can't find end of the entity starting at byte offset 22"}` comes from a response from Telegram servers but root problem maybe with the sonarr bot.

Do you have folders set up in Sonarr? Check [this reply](https://github.com/onedr0p/telegram-sonarr-bot/issues/6#issuecomment-164353460) in the issue above

**Comment by frankjath** [comment] 2016-03-11 00:42
Yes all my TV Shows live `/Volumes/Media_3/tv shows/`

I also have `/Volumes/Media/tv shows` which I no longer use & can't figure out how to get rid of.

**Comment by onedr0p** [comment] 2016-03-11 00:52
Interesting, in both cases there are spaces in the path. I wonder if there's any clue there as to why it doesn't work for you guys?

**Comment by frankjath** [comment] 2016-03-11 01:09
Well its not the spaces, I swiched my path to `/Volumes/Media_3/tvshows/` without the spaces and I restarted `node sonarr.js`

**Comment by onedr0p** [comment] 2016-03-11 01:21
Can you check to see if the _ (in Media_3) is the culprit. My guess here it that uderscores are trying to make it italic in markdown.

Let me explain my thinking: `_this is sentence italic_` =  _this is sentence italic_
When it can't find the closing underscore it errors out.

**Comment by frankjath** [comment] 2016-03-11 01:22
Oh I see I'll check...

**Comment by onedr0p** [comment] 2016-03-11 01:36
You're fine, it's definitely an issue with the bot. The problem is I don't think I can use markdown formatting at all because there seems to be no way of telling telegram to not parse it if there's no matching enclosing underscore (italic) or asterisk (bold). I think I could use [HTML style](https://core.telegram.org/bots/api#html-style) instead.

**Comment by frankjath** [comment] 2016-03-11 02:03
Markdown makes life so much easier...to bad you can't use it. Well thanks for the help I very much appreciate it.

**Comment by crxdelsol** [comment] 2016-04-14 12:34
I have fixed this just now in pull request #45. Waiting for @onedr0p to accept it.
This was annoying me so much I started on debugging it myself.

**Comment by jayrox** [comment] 2016-04-14 15:44
Thanks for looking into this. I'll pull the code and test on my side and
accept the change

**Comment by jayrox** [comment] 2016-04-14 15:52
merged in #45

**Comment by crxdelsol** [comment] 2016-04-14 15:53
Great! The fix was quite logical if you follow the functions and see what parameters other functions are passing through. The destination function is also setting the object keys wwhich were begin transported over there, so the part which I changed was not making any sense before my fix.

**Closed by jayrox** 2016-04-14 15:52 UTC
Labels: bug

**Comment by jayrox** [comment] 2016-04-14 15:55
i think that was just legacy code that wasn't breaking until recently

**Comment by crxdelsol** [comment] 2016-04-14 16:03
I still don't understand why. Since the target function only allows an array as second parameter and an object was given. While all other calls to that same function give an array as it is supposed to do. Maybe a change on the function of the included package, whatever maybe an object was allowed also, don't know exactly.
